from fpdf import FPDF
import os

def generate_report(user, complaint, prediction_result):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(190, 10, txt="Spam Detection Report", ln=1, align="C")
    pdf.line(10, 25, 200, 25)
    
    # User Details
    pdf.ln(10)
    pdf.set_font("Arial", size=12)
    pdf.cell(190, 10, txt=f"Report ID: {complaint.id}", ln=1)
    pdf.cell(190, 10, txt=f"User: {user.name} ({user.email})", ln=1)
    pdf.cell(190, 10, txt=f"Date: {complaint.timestamp.strftime('%Y-%m-%d %H:%M:%S')}", ln=1)
    
    # Content
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(190, 10, txt="Suspicious Message Content:", ln=1)
    pdf.set_font("Arial", size=10)
    pdf.multi_cell(0, 6, txt=complaint.message_content)
    
    # Prediction Results
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    result_text = "FRAUD / SPAM" if prediction_result['prediction'] == 1 else "LEGITIMATE"
    
    # Color coding
    if prediction_result['prediction'] == 1:
        pdf.set_text_color(200, 0, 0) # Red
    else:
        pdf.set_text_color(0, 150, 0) # Green
        
    pdf.cell(190, 10, txt=f"Prediction: {result_text}", ln=1)
    pdf.set_text_color(0, 0, 0) # Reset color
    
    pdf.set_font("Arial", size=12)
    pdf.cell(190, 8, txt=f"Fraud Probability: {prediction_result['fraud_probability']:.2%}", ln=1)
    pdf.cell(190, 8, txt=f"Legitimate Probability: {prediction_result['legit_probability']:.2%}", ln=1)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, txt="Generated by Spam Reporting Portal - Unified Fraud Detection System", align="C")
    
    # Save file
    filename = f"report_{complaint.id}.pdf"
    output_dir = os.path.join("static", "reports")
    os.makedirs(output_dir, exist_ok=True)
    
    # Warning: FPDF output expects a string path
    path = os.path.join(output_dir, filename)
    pdf.output(path)
    
    # Return relative path for web access
    return f"static/reports/{filename}"
