services:
  - type: web
    name: cybershield
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cybershield-db
          property: connectionString

databases:
  - name: cybershield-db
    databaseName: cybershield
    user: cybershield
